# -*- coding: utf-8 -*-
"""Course-Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K70rbg8fxtCg1pfpePJ512SzLbDmlLlc

# Summer 2022 Python for Econ Students Course Project
## Student Name
## نام دانشجو

## Read data
You have to read the data from an excel file.
The excel file can be found here:
https://dl.dropboxusercontent.com/s/xsywvv5p5p8k9kq/MB_Data.xlsx

variable:
MB: Monetary Base
MB_gr: Monetary Base Growth
Expansion: Dummy variabel that is 1 in expansion periods and 0 in recession periods
Recession: Dummy variabel that is 1 in recession periods and 0 in expansion periods
NonOilGDP: Real Non-oil GDP of Iran
NonOilGDPCycle: Deviations of NonOilGDP from it's trends
"""



"""## Preview data
Show a part of data
"""



"""## Slice data
Keep only rows that include data on Expansion and Recession

"""



"""## Plot data
Plot time series data of monetary base growth. 
Add additional background bars that show recession periods.
"""



"""plot the time series data for recession and expansion period in different colors"""



"""## Average Growth of monetary base
The given growth rate is quarterly growth rate
* Calculate and report the average quarterly growth rate
* Calculate and report the average annual growth rate _(note that it's not 4*quarterly rate!)_

"""



"""## Calculate means in expansions and recessions

"""



"""## Test the equality of means of monetary base growth in recession and expansions """



"""##Test the equality of variances of monetary base growth in recessions and expansions"""

