# -*- coding: utf-8 -*-
"""S08-matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AojAbiDsPRksz3tZOqVCEKIELuIDRLSt

**optimize**
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize

def eqn(x):
  return x**2 + x + 2

mymin = minimize(eqn, 0, method='BFGS')

print(mymin)

print(np.repeat(mymin.x,4))

my_x = np.arange(-3,3,.01)
my_y = eqn(my_x)
plt.plot(my_x,my_y)
plt.plot(range(-2,3),np.repeat(mymin.fun,5))
plt.plot(np.repeat(mymin.x,4),range(0,4))
plt.show()

import math
def eqn(x):
  return math.sin(x)

mymin1 = minimize(eqn, 0.1, method='BFGS')
mymin2 = minimize(eqn, 1.1, method='BFGS')
mymin3 = minimize(eqn, 2.1, method='BFGS')
mymin4 = minimize(eqn, math.pi/2, method='BFGS')

print(mymin1)
print(mymin2)
print(mymin3)
print(mymin4)

"""## `matplotlib`"""

import matplotlib.pyplot as plt
import numpy as np

xpoints = np.array([0, 6])
ypoints = np.array([0, 250])
print(xpoints)
plt.plot(xpoints, ypoints, 'o')
plt.show()

xpoints = np.array([1, 2, 6, 8])
ypoints = np.array([3, 8, 1, 10])

plt.plot(ypoints)
plt.show()

x = np.arange(-3,3.1,.1)
y = x ** 2

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt

import numpy as np

xpoints = np.array([1, 2, 6, 8])
ypoints = np.array([0, 250, 300, 200])
ypoints2 = np.array([50, 200, 100, 100])
ypoints3 = np.array([100, 150, 170, 100])

plt.plot(xpoints, ypoints,'--')
plt.plot(xpoints, ypoints2,'o')
plt.plot(xpoints, ypoints3,'-.')
plt.show()

ypoints = np.array([3, 8, 1, 10])

plt.plot(ypoints,marker='2',color='Black',ls='--',linewidth = '1',ms=20,mfc='Aquamarine',mec='r')
plt.show()

"""https://www.w3schools.com/python/matplotlib_markers.asp

"""

plt.plot(ypoints,marker='o',color='#555555',ls='--',linewidth = '4',ms=12,mfc='Aquamarine',mec='r')
plt.show()



import matplotlib.pyplot as plt
import numpy as np

ypoints = np.array([3, 8, 1, 10])

font1 = {'family':'serif','color':'blue','size':20}

plt.plot(ypoints,marker='o',color='b',ls='--',linewidth = '4',ms=12,mfc='Aquamarine',mec='r')
plt.xlabel("my x")
plt.ylabel("my y")
plt.title("My Plot",fontdict=font1,loc='left')
plt.grid(axis='y',color='r',ls='--',linewidth=.5)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

#plot 1:
x = np.array([0, 1, 2, 3])
y = np.array([3, 8, 1, 10])

plt.subplot(2, 3, 1)
plt.plot(x,y)
plt.title("t1")

#plot 2:
x = np.array([0, 1, 2, 3])
y = np.array([10, 20, 30, 40])

plt.subplot(2, 3, 5)
plt.plot(x,y)
plt.title("t2")


plt.subplot(2, 3, 3)
plt.plot(x,y)
plt.title("t3")

plt.suptitle("Title")

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([5,7,8,7,2,17,2,9,4,11,12,9,6])
y = np.array([99,86,87,88,111,86,103,87,94,78,77,85,86])

plt.scatter(x, y,color='pink')


x = np.array([2,2,8,1,15,8,12,9,7,3,11,4,7,14,12])
y = np.array([100,105,84,105,90,99,90,95,94,100,79,112,91,80,85])
plt.scatter(x, y,color="#777777")


plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([4,2,6,8])
y = np.array([34,33,65,10])
cols = np.array(['blue','brown','pink','red'])
plt.scatter(x,y,c=cols)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([4,2,6,8])
y = np.array([34,33,65,10])
z = np.array([3,35,1000,53])
plt.scatter(x,y,c=z,cmap='Pastel1',s=z)
plt.show()

"""https://www.w3schools.com/python/matplotlib_scatter.asp

"""

import matplotlib.pyplot as plt
import numpy as np

x = np.array([5,7,8,7,2,17,2,9,4,11,12,9,6])
y = np.array([99,86,87,88,111,86,103,87,94,78,77,85,86])
sizes = np.array([20,50,100,200,500,1000,60,90,10,300,600,800,75])

plt.scatter(x, y, s=sizes, alpha=0.5)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array(["A", "B", "C", "D"])
y = np.array([3, 8, 1, 10])

plt.barh(x,y,color='red')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([35, 25, 205, 15])
st = np.array(['a','b','c','d'])
plt.pie(y,labels=st,startangle=50,explode=np.repeat(.2,4))
plt.legend(["A","B","C","D"],title="Legend title")
plt.show()